### ISSUE TITLE
Release rematch2 2.1.1

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rematch2#11]
Prepare for release:

* [ ] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [x] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Bump dev version

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by gaborcsardi** [comment]
Errors on R-devel:

```
** running examples for arch 'i386' ... ERROR
Running examples in 'rematch2-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: re_exec
> ### Title: Extract Data From First Regular Expression Match Into a Data
> ###   Frame
> ### Aliases: re_exec $.rematch_records $.rematch_allrecords
> 
> ### ** Examples
> 
> name_rex <- paste0(
+   "(?<first>[[:upper:]][[:lower:]]+) ",
+   "(?<last>[[:upper:]][[:lower:]]+)"
+ )
> notables <- c(
+   "  Ben Franklin and Jefferson Davis",
+   "\tMillard Fillmore"
+ )
> # Match first occurrence
> pos <- re_exec(notables, name_rex)
> pos
Error: Input must be a vector, not a `rematch_records` object.
Backtrace:
     x
  1. +-(function (x, ...) ...
  2. +-tibble:::print.tbl(x)
  3. | +-cli::cat_line(format(x, ..., n = n, width = width, n_extra = n_extra))
  4. | | \-base::paste0(..., collapse = "\n")
  5. | +-base::format(x, ..., n = n, width = width, n_extra = n_extra)
  6. | \-tibble:::format.tbl(x, ..., n = n, width = width, n_extra = n_extra)
  7. |   \-tibble::trunc_mat(x, n = n, width = width, n_extra = n_extra)
  8. |     +-base::as.data.frame(head(x, n))
  9. |     +-utils::head(x, n)
 10. |     \-utils:::head.data.frame(x, n)
 11. |       +-base::do.call("[", args)
 12. |       +-x[1:2, , drop = FALSE]
 13. |       \-tibble:::`[.tbl_df`(x, 1:2, , drop = FALSE)
 14. |         \-tibble:::tbl_subset_row(xo, i = i, i_arg)
 15. |           \-base::lapply(unclass(x), vec_slice, i = i)
 16. |             \-vctrs:::FUN(X[[i]], ...)
 17. \-vctrs:::stop_scalar_type(...)
 18.   \-vctrs:::stop_vctrs(msg, "vctrs_error_scala
Execution halted
```

and the same on 64 bit.

**Comment by gaborcsardi** [comment]
@krlmlr Will this be fixed with the new tibble? 

https://win-builder.r-project.org/NO8gWoKc76zF/00check.log

**Comment by gaborcsardi** [comment]
I can't repro this on macOS R-devel or R-hub's R-devel... could it be using some dev version of tibble or vctrs on Win-builder?

**Comment by gaborcsardi** [comment]
I figure I can just submit it and see....

**Comment by krlmlr** [comment]
Let me try to repro first, maybe?

**Comment by krlmlr** [comment]
Oh, it could be an *old* version of vctrs. Reminds me to bump the dependency.

**Comment by gaborcsardi** [comment]
Well, I submitted already, sry, and it was clean on R-devel.

**Comment by krlmlr** [comment]
I guess it will sort itself out. Thanks!

**Comment by gaborcsardi** [comment]
It is turns out to be bad with new tibble, then I'll just tell them and so a quick update...

**Comment by krlmlr** [comment]
About to submit a follow-up PR. Let's hope there's a failure downstream.

**Comment by gaborcsardi** [comment]
No, on CRAN.... anyway, just go on with tibble, and tell them we did not fitch rematch2 properly and I would submit another version. You can cc me.
