### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by mdlincoln** [r-lib/rematch2#4]
Do you plan on updating the CRAN version of this package now that it has the new `bind_re_match` function?

**Comment by gaborcsardi** [comment]
Sure.

**Comment by gaborcsardi** [comment]
Please ping me again if I forget in the next ~5 days. Thanks!

**Comment by mdlincoln** [comment]
pinging again :)

**Comment by mdlincoln** [comment]
pinging again!

**Comment by gaborcsardi** [comment]
Good pinging!

**Comment by flying-sheep** [comment]
There’s a CRAN release, but it doesn’t contain the newest PR #3

**Comment by gaborcsardi** [comment]
It took a while, sorry....

**Comment by flying-sheep** [comment]
thank you!
