### ISSUE TITLE
Use backports or DIY trimws

### ISSUE THREAD

**Issue by jennybc** [r-lib/rematch2#5]
For the next CRAN release, can you take your favourite action to make rematch2 ok down to tidyverse/r-lib target of R >= 3.1? The culprit is `trimws()`.

**Comment by jennybc** [comment]
Hold on ... maybe I'm getting this from something else? Will resolve.

**Comment by jennybc** [comment]
Sorry, moving this over to curl 😳

**Comment by gaborcsardi** [comment]
I bit ahead of you: https://github.com/jeroen/curl/pull/139 :)
