### ISSUE TITLE
Should rematch2 really import tibble?

### ISSUE THREAD

**Issue by jennybc** [r-lib/rematch2#6]
Food for thought. Maybe rematch2 should not import tibble.

I note this is in direct contradiction with at least one other issue (#2), though.

**Comment by gaborcsardi** [comment]
Yeah. It probably should not.

**Comment by gaborcsardi** [comment]
I cannot remove it, actually, because then it would return a different class....

**Comment by jennybc** [comment]
rematch3!!

**Comment by gaborcsardi** [comment]
We'll just keep importing tibble, I suppose. And we'll have a standalone rematch2 version, that you can just copy into packages, if no dependencies are crucial.
